# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
