# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170604_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='documents',
            field=models.ManyToManyField(related_name='events', to='events.Document'),
        ),
    ]
