# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170604_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.Event')),
            ],
        ),
    ]
