# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_comment'),
        ('events', '0006_eventquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventquestions',
            name='id',
        ),
        migrations.AddField(
            model_name='eventquestions',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Question'),
            preserve_default=False,
        ),
    ]
