# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20170604_0201'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='documents',
            field=models.ManyToManyField(related_name='events', to='documents.Document'),
        ),
    ]
