# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='events', to='documents.Document'),
        ),
    ]
