# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        ('events', '0003_auto_20170604_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question.Question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.Event')),
            ],
            bases=('question.question',),
        ),
    ]
