# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventquestion',
            old_name='question',
            new_name='event',
        ),
    ]
