# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_canceld',
            field=models.BooleanField(default=False),
        ),
    ]
