# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_booking_is_canceld'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='EventBookingView',
        ),
    ]
