# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170605_0604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventBookingView',
            new_name='EventBooking',
        ),
    ]
