# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170605_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbookinglist',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
