# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventbookinglist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbookinglist',
            name='user',
        ),
    ]
