# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_remove_eventbookinglist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbookinglist',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
