# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventbookinglist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbookinglist',
            name='detail',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbookinglist',
            name='title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
