# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20170605_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbookinglist',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='eventbookinglist',
            name='title',
        ),
    ]
