# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
