# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20170607_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rating.Movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='own_ratings', to='rating.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.IntegerField(),
        ),
    ]
