# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20170607_1009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='movie',
            name='mid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
