# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20170607_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.IntegerField(unique=True),
        ),
    ]
