# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_auto_20170610_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUploadTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('tid', models.CharField(max_length=255)),
            ],
        ),
    ]
