# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_datauploadtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauploadtask',
            name='progress',
            field=models.TextField(null=True),
        ),
    ]
