# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_datauploadtask_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauploadtask',
            name='upload_flag',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
