# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_datauploadtask_upload_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datauploadtask',
            old_name='upload_flag',
            new_name='complete',
        ),
    ]
