# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0010_auto_20170611_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauploadtask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
