# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0011_auto_20170611_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauploadtask',
            name='progress',
            field=models.FloatField(null=True),
        ),
    ]
