# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('detail', models.TextField()),
                ('start', models.DateTimeField()),
            ],
        ),
    ]
