# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20170604_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='updated',
        ),
        migrations.AddField(
            model_name='document',
            name='uploaed',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
